/**
 * Static seed fixtures. All data is fabricated — no real personal info.
 */

export const COUNTRIES = [
  {
    iso_code: "ZA",
    name: "South Africa",
    currency: "ZAR",
    tax_authority: "SARS",
    timezone: "Africa/Johannesburg",
    flag_emoji: "🇿🇦",
    cycle_cutoff_day: 25,
    ach_lag_days: 1,
    filing_forms: ["EMP201", "EMP501", "IRP5", "UI19", "UIF"],
  },
  {
    iso_code: "GB",
    name: "United Kingdom",
    currency: "GBP",
    tax_authority: "HMRC",
    timezone: "Europe/London",
    flag_emoji: "🇬🇧",
    cycle_cutoff_day: 20,
    ach_lag_days: 1,
    filing_forms: ["P60", "P11D", "P11D(b)", "RTI-FPS", "P45"],
  },
  {
    iso_code: "US",
    name: "United States",
    currency: "USD",
    tax_authority: "IRS",
    timezone: "America/New_York",
    flag_emoji: "🇺🇸",
    cycle_cutoff_day: 25,
    ach_lag_days: 2,
    filing_forms: ["W-2", "W-3", "941", "940", "1099-NEC"],
  },
  {
    iso_code: "DE",
    name: "Germany",
    currency: "EUR",
    tax_authority: "Finanzamt",
    timezone: "Europe/Berlin",
    flag_emoji: "🇩🇪",
    cycle_cutoff_day: 20,
    ach_lag_days: 1,
    filing_forms: ["LSt-Anmeldung", "SV-Meldung", "Lohnabrechnung"],
  },
  {
    iso_code: "AU",
    name: "Australia",
    currency: "AUD",
    tax_authority: "ATO",
    timezone: "Australia/Sydney",
    flag_emoji: "🇦🇺",
    cycle_cutoff_day: 20,
    ach_lag_days: 1,
    filing_forms: ["PAYG", "STP", "Super", "Payment-Summary"],
  },
  {
    iso_code: "AE",
    name: "United Arab Emirates",
    currency: "AED",
    tax_authority: "MoHRE",
    timezone: "Asia/Dubai",
    flag_emoji: "🇦🇪",
    cycle_cutoff_day: 25,
    ach_lag_days: 1,
    filing_forms: ["WPS", "GOSI"],
  },
];

/** 2026 + 2027 public holidays, 10-15 per country. Snapshot from OpenHolidaysAPI. */
export const HOLIDAYS: Record<string, { date: string; name: string }[]> = {
  ZA: [
    { date: "2026-01-01", name: "New Year's Day" },
    { date: "2026-03-21", name: "Human Rights Day" },
    { date: "2026-04-03", name: "Good Friday" },
    { date: "2026-04-06", name: "Family Day" },
    { date: "2026-04-27", name: "Freedom Day" },
    { date: "2026-05-01", name: "Workers' Day" },
    { date: "2026-06-16", name: "Youth Day" },
    { date: "2026-08-09", name: "National Women's Day" },
    { date: "2026-09-24", name: "Heritage Day" },
    { date: "2026-12-16", name: "Day of Reconciliation" },
    { date: "2026-12-25", name: "Christmas Day" },
    { date: "2026-12-26", name: "Day of Goodwill" },
    { date: "2027-01-01", name: "New Year's Day" },
    { date: "2027-03-22", name: "Human Rights Day (observed)" },
  ],
  GB: [
    { date: "2026-01-01", name: "New Year's Day" },
    { date: "2026-04-03", name: "Good Friday" },
    { date: "2026-04-06", name: "Easter Monday" },
    { date: "2026-05-04", name: "Early May Bank Holiday" },
    { date: "2026-05-25", name: "Spring Bank Holiday" },
    { date: "2026-08-31", name: "Summer Bank Holiday" },
    { date: "2026-12-25", name: "Christmas Day" },
    { date: "2026-12-28", name: "Boxing Day (observed)" },
    { date: "2027-01-01", name: "New Year's Day" },
    { date: "2027-04-02", name: "Good Friday" },
  ],
  US: [
    { date: "2026-01-01", name: "New Year's Day" },
    { date: "2026-01-19", name: "Martin Luther King Jr. Day" },
    { date: "2026-02-16", name: "Presidents' Day" },
    { date: "2026-05-25", name: "Memorial Day" },
    { date: "2026-06-19", name: "Juneteenth" },
    { date: "2026-07-03", name: "Independence Day (observed)" },
    { date: "2026-09-07", name: "Labor Day" },
    { date: "2026-11-26", name: "Thanksgiving" },
    { date: "2026-12-25", name: "Christmas Day" },
    { date: "2027-01-01", name: "New Year's Day" },
  ],
  DE: [
    { date: "2026-01-01", name: "Neujahr" },
    { date: "2026-04-03", name: "Karfreitag" },
    { date: "2026-04-06", name: "Ostermontag" },
    { date: "2026-05-01", name: "Tag der Arbeit" },
    { date: "2026-05-14", name: "Christi Himmelfahrt" },
    { date: "2026-05-25", name: "Pfingstmontag" },
    { date: "2026-10-03", name: "Tag der Deutschen Einheit" },
    { date: "2026-12-25", name: "1. Weihnachtstag" },
    { date: "2026-12-26", name: "2. Weihnachtstag" },
    { date: "2027-01-01", name: "Neujahr" },
  ],
  AU: [
    { date: "2026-01-01", name: "New Year's Day" },
    { date: "2026-01-26", name: "Australia Day" },
    { date: "2026-04-03", name: "Good Friday" },
    { date: "2026-04-06", name: "Easter Monday" },
    { date: "2026-04-25", name: "ANZAC Day" },
    { date: "2026-06-08", name: "King's Birthday" },
    { date: "2026-12-25", name: "Christmas Day" },
    { date: "2026-12-28", name: "Boxing Day (observed)" },
    { date: "2027-01-01", name: "New Year's Day" },
  ],
  AE: [
    { date: "2026-01-01", name: "New Year's Day" },
    { date: "2026-04-10", name: "Eid al-Fitr" },
    { date: "2026-04-11", name: "Eid al-Fitr Holiday" },
    { date: "2026-04-12", name: "Eid al-Fitr Holiday" },
    { date: "2026-06-16", name: "Eid al-Adha" },
    { date: "2026-06-17", name: "Eid al-Adha Holiday" },
    { date: "2026-06-18", name: "Eid al-Adha Holiday" },
    { date: "2026-07-07", name: "Islamic New Year" },
    { date: "2026-09-15", name: "Prophet's Birthday" },
    { date: "2026-12-02", name: "UAE National Day" },
    { date: "2026-12-03", name: "UAE National Day Holiday" },
  ],
};

export const FX_PAIRS = [
  { base_currency: "ZAR", quote_currency: "USD" },
  { base_currency: "GBP", quote_currency: "USD" },
  { base_currency: "EUR", quote_currency: "USD" },
  { base_currency: "AUD", quote_currency: "USD" },
  { base_currency: "AED", quote_currency: "USD" },
];

/** Mid-market rates (approx April 2026) for the above pairs — base -> USD */
export const FX_BASELINE: Record<string, number> = {
  ZAR: 0.0535,
  GBP: 1.27,
  EUR: 1.08,
  AUD: 0.66,
  AED: 0.2723,
};

/** Per-country salary bands in local currency, monthly gross. */
export const SALARY_BANDS: Record<string, { min: number; max: number }> = {
  ZA: { min: 35_000, max: 120_000 },
  GB: { min: 3_200, max: 9_500 },
  US: { min: 5_500, max: 18_000 },
  DE: { min: 4_500, max: 11_000 },
  AU: { min: 7_000, max: 15_000 },
  AE: { min: 18_000, max: 45_000 },
};

export const ROLE_TITLES = [
  "Payroll Operations Associate",
  "Software Engineer",
  "Senior Software Engineer",
  "Staff Engineer",
  "Product Designer",
  "Legal Counsel",
  "Finance Analyst",
  "Customer Success Manager",
  "Account Executive",
  "Data Scientist",
  "People Partner",
  "Technical Writer",
  "Operations Manager",
  "Product Manager",
  "Marketing Manager",
];

export const EMPLOYEE_DISTRIBUTION = {
  ZA: 18,
  GB: 11,
  US: 8,
  DE: 5,
  AU: 4,
  AE: 2,
};
