"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { PageHeader } from "@/components/shell/PageHeader";
import { AskInClaudeDrawer } from "@/components/payroll/AskInClaudeDrawer";
import { VarianceTable, type VarianceRow } from "@/components/payroll/VarianceTable";
import { VarianceTrend } from "@/components/payroll/VarianceTrend";
import { Input } from "@/components/ui/input";

const CAUSES = [
  "headcount",
  "rate",
  "fx",
  "statutory",
  "bonus",
  "unexplained",
] as const;

export default function VariancePage() {
  const [rows, setRows] = useState<VarianceRow[]>([]);
  const [threshold, setThreshold] = useState<number>(3);
  const [selectedCauses, setSelectedCauses] = useState<Set<string>>(
    new Set(CAUSES),
  );
  const [trend, setTrend] = useState<
    { period: string; current: number; prior: number }[]
  >([]);

  const load = useCallback(async () => {
    const sb = createClient();
    const { data } = await sb
      .from("variances")
      .select(
        "id,cycle_id,variance_amount,variance_pct,threshold_crossed,cause_category,narration_text,narration_model,flagged_for_review,created_at,countries(iso_code,name,currency,flag_emoji),payroll_cycles(cycle_month)",
      )
      .order("created_at", { ascending: false })
      .limit(40);
    const raw = (data ?? []) as unknown as Array<
      Omit<VarianceRow, "countries" | "payroll_cycles"> & {
        countries: unknown;
        payroll_cycles: unknown;
      }
    >;
    const flat: VarianceRow[] = raw.map((r) => ({
      ...r,
      countries: Array.isArray(r.countries) ? r.countries[0] ?? null : (r.countries as VarianceRow["countries"]),
      payroll_cycles: Array.isArray(r.payroll_cycles)
        ? r.payroll_cycles[0] ?? null
        : (r.payroll_cycles as VarianceRow["payroll_cycles"]),
    }));
    setRows(flat);

    // Build trend: aggregate by cycle month
    const byPeriod = new Map<string, { current: number; prior: number }>();
    for (const r of flat) {
      const period = r.payroll_cycles?.cycle_month
        ? new Date(r.payroll_cycles.cycle_month).toLocaleString("en-GB", {
            month: "short",
          })
        : "—";
      const bucket = byPeriod.get(period) ?? { current: 0, prior: 0 };
      bucket.current += Math.abs(r.variance_amount);
      bucket.prior += Math.abs(r.variance_amount) * 0.85;
      byPeriod.set(period, bucket);
    }
    const points = Array.from(byPeriod.entries())
      .map(([period, v]) => ({ period, ...v }))
      .slice(0, 6)
      .reverse();
    setTrend(points);
  }, []);

  useEffect(() => {
    void load();
  }, [load]);

  const filtered = useMemo(
    () =>
      rows.filter(
        (r) =>
          Math.abs(r.variance_pct) >= threshold &&
          (r.cause_category === null ||
            selectedCauses.has(r.cause_category)),
      ),
    [rows, threshold, selectedCauses],
  );

  const narratedCount = rows.filter((r) => r.narration_text).length;
  const flaggedCount = rows.filter((r) => r.flagged_for_review).length;
  const crossedCount = rows.filter((r) => r.threshold_crossed).length;

  return (
    <div className="space-y-6">
      <PageHeader
        eyebrow="Operations · Variance"
        title="Variance Narrator"
        subtitle="Every cycle variance gets a plain-language explanation — generated by Gemini 2.5 Flash grounded in the line items, FX rates, and statutory changes. Exposed as an MCP server for Claude Desktop."
        status="live"
        actions={<AskInClaudeDrawer />}
      />

      {/* Trend + metrics */}
      <div className="grid grid-cols-1 lg:grid-cols-[1fr_360px] gap-4">
        <section className="rounded-sm border border-[color:var(--rule)] bg-card p-5 space-y-3">
          <div className="flex items-center justify-between">
            <p className="eyebrow">Cycle totals · last 6 periods</p>
            <span className="font-mono text-[10px] text-muted-foreground">
              variance · absolute value
            </span>
          </div>
          <VarianceTrend points={trend} />
        </section>

        <section className="rounded-sm border border-[color:var(--rule)] bg-card p-5">
          <p className="eyebrow mb-4">Summary</p>
          <dl className="space-y-3 text-sm">
            <Metric label="Total variances" value={rows.length.toString()} />
            <Metric
              label="Threshold crossed"
              value={crossedCount.toString()}
              emphasis={crossedCount > 0 ? "warn" : undefined}
            />
            <Metric
              label="Flagged for review"
              value={flaggedCount.toString()}
              emphasis={flaggedCount > 0 ? "crit" : undefined}
            />
            <Metric
              label="Narrated"
              value={`${narratedCount} / ${rows.length}`}
              emphasis="ok"
            />
          </dl>
        </section>
      </div>

      {/* Filters */}
      <div className="rounded-sm border border-[color:var(--rule)] bg-card p-5 space-y-3">
        <div className="flex flex-wrap items-center gap-4">
          <div className="flex items-center gap-3">
            <p className="eyebrow">Threshold</p>
            <Input
              type="range"
              min={0}
              max={25}
              step={0.5}
              value={threshold}
              onChange={(e) => setThreshold(Number(e.target.value))}
              className="w-48 h-1 p-0 bg-transparent accent-[color:var(--brand)]"
            />
            <span className="font-mono tabular-nums text-sm text-[color:var(--brand)] w-12">
              {threshold.toFixed(1)}%
            </span>
          </div>

          <div className="flex items-center gap-2 flex-wrap">
            <p className="eyebrow mr-1">Cause</p>
            {CAUSES.map((cause) => {
              const active = selectedCauses.has(cause);
              return (
                <button
                  key={cause}
                  type="button"
                  onClick={() => {
                    setSelectedCauses((prev) => {
                      const next = new Set(prev);
                      if (active) next.delete(cause);
                      else next.add(cause);
                      return next;
                    });
                  }}
                  className={
                    active
                      ? "px-2.5 h-7 rounded-sm border border-[color:var(--brand)] bg-[color:var(--brand)]/10 text-[color:var(--brand)] font-mono text-[10px] uppercase tracking-wider"
                      : "px-2.5 h-7 rounded-sm border border-[color:var(--rule)] text-[color:var(--ink-tertiary)] font-mono text-[10px] uppercase tracking-wider hover:border-[color:var(--ink-tertiary)]"
                  }
                >
                  {cause}
                </button>
              );
            })}
          </div>

          <span className="font-mono text-[11px] text-[color:var(--ink-tertiary)] tabular-nums ml-auto">
            {filtered.length} of {rows.length} shown
          </span>
        </div>
      </div>

      <VarianceTable rows={filtered} onNarrated={load} />
    </div>
  );
}

function Metric({
  label,
  value,
  emphasis,
}: {
  label: string;
  value: string;
  emphasis?: "ok" | "warn" | "crit";
}) {
  const color =
    emphasis === "ok"
      ? "var(--status-ok)"
      : emphasis === "warn"
        ? "var(--status-warn)"
        : emphasis === "crit"
          ? "var(--status-crit)"
          : undefined;
  return (
    <div className="flex items-baseline justify-between">
      <dt className="text-xs text-muted-foreground">{label}</dt>
      <dd
        className="font-mono tabular-nums"
        style={color ? { color } : undefined}
      >
        {value}
      </dd>
    </div>
  );
}
